#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Chris Carvache

# All-in-one boot: self-generate secrets on first run (Community Apps
# templates can't generate secrets, so the container must), wire Laravel to
# /data/.env, migrate, stamp the instance's Reverb key into the PWA bundle,
# then hand off to supervisord.
set -e

if [ ! -f /data/.env ]; then
  echo "==> first boot: generating secrets into /data/.env"
  umask 077
  cat > /data/.env <<EOF
# Generated by the mybabynotes all-in-one container on first boot.
# Back this file up together with database.sqlite — losing APP_KEY strands
# the data encrypted with it. Optional overrides (MAIL_*, APP_URL,
# REVERB_ALLOWED_ORIGINS, ...) can be appended here; container env vars
# still win over this file.
APP_KEY=base64:$(openssl rand -base64 32)
REVERB_APP_ID=babylog
REVERB_APP_KEY=$(openssl rand -hex 16)
REVERB_APP_SECRET=$(openssl rand -hex 24)
EOF
  umask 022
fi

# refuse to boot half-configured — a bad APP_KEY now beats undecryptable data later
grep -q '^APP_KEY=base64:..*' /data/.env || {
  echo "ERROR: /data/.env has no APP_KEY — fix it, or delete /data/.env (NOT the sqlite file) to regenerate" >&2
  exit 1
}
REVERB_KEY=$(sed -n 's/^REVERB_APP_KEY=//p' /data/.env | tail -1)
[ -n "$REVERB_KEY" ] || {
  echo "ERROR: /data/.env has no REVERB_APP_KEY — fix it, or delete /data/.env (NOT the sqlite file) to regenerate" >&2
  exit 1
}

# Laravel reads .env from the app root; point it at the persisted one
ln -sf /data/.env /var/www/html/.env

: "${DB_CONNECTION:=sqlite}"

# The appliance default is a SQLite file this container owns. Pointing
# DB_CONNECTION at a Postgres of your own is supported (the image carries
# pdo_pgsql), and then none of the file prep applies — but /data still holds
# the generated .env, so it stays ours either way.
if [ "$DB_CONNECTION" = "sqlite" ]; then
  # export, not a bare shell default: php inherits the environment, so an
  # unexported assignment would leave Laravel on its own database_path()
  # fallback while we touched a file it never opens
  export DB_DATABASE="${DB_DATABASE:-/data/database.sqlite}"
  [ -f "$DB_DATABASE" ] || touch "$DB_DATABASE"
fi

# The PWA bundle bakes a placeholder Reverb key at image build time; stamp
# this instance's real key (public by protocol design, but per-instance) over
# it. On a plain restart the stamp is already there — that's fine.
stamped=$(grep -rl '__BABYLOG_REVERB_KEY__' /usr/share/nginx/html 2>/dev/null || true)
if [ -n "$stamped" ]; then
  echo "$stamped" | while read -r f; do
    sed -i "s/__BABYLOG_REVERB_KEY__/$REVERB_KEY/g" "$f"
  done
elif ! grep -rq "$REVERB_KEY" /usr/share/nginx/html/assets 2>/dev/null; then
  # not fatal: the app degrades to its 60s heartbeat poll without websockets
  echo "WARNING: the served bundle carries a different REVERB_APP_KEY (was /data/.env edited after boot?) — realtime will fall back to polling until the container is recreated" >&2
fi

if [ "$DB_CONNECTION" = "sqlite" ]; then
  php artisan migrate --force
else
  # An external Postgres may not be accepting connections yet on a cold boot:
  # retry briefly so the log says so instead of the container crash-looping.
  n=0
  until php artisan migrate --force; do
    n=$((n + 1))
    [ "$n" -ge 10 ] && { echo "ERROR: database unreachable after 10 attempts" >&2; exit 1; }
    echo "==> database not ready, retrying in 3s ($n/10)" >&2
    sleep 3
  done
fi

# Everything PHP runs as www-data from here on — fpm workers via the pool
# config, Reverb / schedule:work / mqtt:listen via supervisord's `user=`
# (only supervisord and nginx, on port 80, stay root). The SQLite file + its
# transient journal (dir write!), the generated .env, and storage/ for the
# file cache, compiled mail views and the scheduler's lock files must be
# theirs. This runs AFTER migrate so anything the root-side boot created is
# handed over too instead of blocking the unprivileged processes later.
chown -R www-data:www-data /data /var/www/html/storage /var/www/html/bootstrap/cache

# opt-in realip for the rate-limit zones (TRUSTED_PROXIES env)
/usr/local/bin/real-ip.sh

exec supervisord -c /etc/supervisord.conf
